%% node-b
flowchart LR
	node-b[Node B]
	node-d[Node D]
	node-a[KnowledgeNode node-a]
	style node-a stroke-dasharray: 5 5

	node-b --> node-d
	node-d --> node-b
	node-d -.-> node-a
	node-a -.-> node-d

	software-1([Software Component 1])
	node-b --> software-1

	809bfbd3{{damageValue : 100.5}}
	809bfbd3 -.-o software-1
	9a3d3038{{isCritical : true}}
	9a3d3038 -.-o software-1
